# Generated by Django 6.0.6 on 2026-07-05 11:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VisitorSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.UUIDField(db_index=True, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("browser", models.CharField(blank=True, max_length=100, null=True)),
                ("os", models.CharField(blank=True, max_length=100, null=True)),
                ("referrer", models.TextField(blank=True, null=True)),
                ("utm_source", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Visitor Session",
                "verbose_name_plural": "Visitor Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("pageview", "Pageview"),
                            ("cta_click", "CTA Click"),
                            ("form_submit", "Form Submit"),
                            ("form_abandon", "Form Abandon"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("page_url", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="tracking.visitorsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Event",
                "verbose_name_plural": "Tracking Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "event_type"],
                        name="tracking_tr_session_74d9f8_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="tracking_tr_event_t_69dd63_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestionInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_id", models.CharField(db_index=True, max_length=100)),
                ("serie", models.CharField(blank=True, max_length=50, null=True)),
                ("time_spent_seconds", models.FloatField(default=0.0)),
                ("revisit_count", models.IntegerField(default=0)),
                ("order_index", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_interactions",
                        to="tracking.visitorsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Interaction",
                "verbose_name_plural": "Question Interactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "question_id"],
                        name="tracking_qu_session_a947ba_idx",
                    ),
                    models.Index(
                        fields=["session", "-created_at"],
                        name="tracking_qu_session_81d7a5_idx",
                    ),
                ],
                "unique_together": {("session", "question_id", "order_index")},
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.TextField()),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to="tracking.visitorsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page View",
                "verbose_name_plural": "Page Views",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "-created_at"],
                        name="tracking_pa_session_3df481_idx",
                    )
                ],
            },
        ),
    ]
