# Generated by Django 6.0.6 on 2026-07-08 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0010_clientdossiercounter_clientdossier_and_more"),
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitorsession",
            name="client_dossier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visitor_sessions",
                to="audits.clientdossier",
            ),
        ),
    ]
