# Generated by Django 6.0.6 on 2026-07-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0003_citation_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citation",
            name="source",
            field=models.CharField(max_length=180),
        ),
    ]
