# Generated by Django 6.0.6 on 2026-07-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0004_citation_source_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="annee",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name="citation",
            index=models.Index(fields=["auteur"], name="citation_auteur_idx"),
        ),
        migrations.AddIndex(
            model_name="citation",
            index=models.Index(fields=["source"], name="citation_source_idx"),
        ),
        migrations.AddIndex(
            model_name="citation",
            index=models.Index(fields=["langue"], name="citation_langue_idx"),
        ),
        migrations.AddIndex(
            model_name="citation",
            index=models.Index(fields=["theme"], name="citation_theme_idx"),
        ),
        migrations.AddIndex(
            model_name="citation",
            index=models.Index(
                fields=["actif", "verifie"], name="citation_publication_idx"
            ),
        ),
    ]
