# Generated by Django 6.0.6 on 2026-07-04 21:32

import django.db.models.deletion
from django.db import migrations, models


MOTIFS = [
    ("Demande d'intervention", 120, "horaire_precis", 10),
    ("Réunion de partenariat", 210, "demi_journee", 20),
    ("Entretien de suivi", 60, "horaire_precis", 30),
    ("Formation", 420, "journee_complete", 40),
    ("Premier entretien d'audit", 30, "horaire_precis", 50),
    ("Autre", 60, "horaire_precis", 60),
]

RAISONS = [
    "Mon site n'apparaît pas dans Google",
    "Je veux comprendre mon audit reçu",
    "Je souhaite un accompagnement sur la durée",
    "J'ai un problème technique urgent sur mon site",
    "Je veux discuter d'un partenariat",
    "Je cherche une formation pour mon équipe",
    "Question sur un devis / une facture",
    "Autre demande",
]


def seed_rdv_reference_data(apps, _schema_editor):
    motif = apps.get_model("audits", "Motif")
    raison_appel = apps.get_model("audits", "RaisonAppel")

    for nom, duree_minutes, creneau_type, ordre in MOTIFS:
        motif.objects.get_or_create(
            nom=nom,
            defaults={
                "duree_minutes": duree_minutes,
                "creneau_type": creneau_type,
                "actif": True,
                "ordre": ordre,
            },
        )

    for ordre, nom in enumerate(RAISONS, start=10):
        raison_appel.objects.get_or_create(nom=nom, defaults={"actif": True, "ordre": ordre})


def unseed_rdv_reference_data(apps, _schema_editor):
    motif = apps.get_model("audits", "Motif")
    raison_appel = apps.get_model("audits", "RaisonAppel")
    motif.objects.filter(nom__in=[item[0] for item in MOTIFS]).delete()
    raison_appel.objects.filter(nom__in=RAISONS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0006_citation_numero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120, unique=True)),
                ("duree_minutes", models.PositiveIntegerField(default=60)),
                (
                    "creneau_type",
                    models.CharField(
                        choices=[
                            ("horaire_precis", "Horaire précis"),
                            ("demi_journee", "Demi-journée"),
                            ("journee_complete", "Journée complète"),
                        ],
                        default="horaire_precis",
                        max_length=24,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("ordre", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="RaisonAppel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=160, unique=True)),
                ("actif", models.BooleanField(default=True)),
                ("ordre", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="CreneauCalendrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("libre", "Libre"),
                            ("reserve_audit", "Réservé audit"),
                            ("reserve_intervention", "Réservé intervention"),
                            ("bloque", "Bloqué"),
                        ],
                        db_index=True,
                        default="libre",
                        max_length=24,
                    ),
                ),
                ("urgence", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "motif_reserve",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creneaux_reserves",
                        to="audits.motif",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="RdvContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=80)),
                ("nom", models.CharField(max_length=80)),
                ("email", models.EmailField(db_index=True, max_length=180)),
                ("telephone", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audit_dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rdv_contacts",
                        to="audits.auditdossier",
                    ),
                ),
            ],
            options={
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Rdv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urgence", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("confirme", "Confirmé"), ("annule", "Annulé")],
                        default="confirme",
                        max_length=16,
                    ),
                ),
                ("notification_status", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creneaux",
                    models.ManyToManyField(
                        related_name="rdvs", to="audits.creneaucalendrier"
                    ),
                ),
                (
                    "motif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rdvs",
                        to="audits.motif",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rdvs",
                        to="audits.rdvcontact",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="creneaucalendrier",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creneaux",
                to="audits.rdvcontact",
            ),
        ),
        migrations.CreateModel(
            name="RdvRaison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audits.raisonappel",
                    ),
                ),
                (
                    "rdv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="audits.rdv"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rdv",
            name="raisons",
            field=models.ManyToManyField(
                blank=True,
                related_name="rdvs",
                through="audits.RdvRaison",
                to="audits.raisonappel",
            ),
        ),
        migrations.CreateModel(
            name="RdvRappel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_rappel",
                    models.CharField(
                        choices=[
                            ("veille", "La veille"),
                            ("une_heure", "Une heure avant"),
                        ],
                        max_length=16,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("last_error", models.TextField(blank=True)),
                (
                    "rdv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rappels",
                        to="audits.rdv",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.AddIndex(
            model_name="creneaucalendrier",
            index=models.Index(
                fields=["date", "statut"], name="creneau_date_statut_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rdvraison",
            unique_together={("rdv", "raison")},
        ),
        migrations.AlterUniqueTogether(
            name="rdvrappel",
            unique_together={("rdv", "type_rappel")},
        ),
        migrations.RunPython(seed_rdv_reference_data, unseed_rdv_reference_data),
    ]
