# Generated by Django 6.0.6 on 2026-07-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0008_refonte_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditreponse",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditreponse",
            name="nom_signataire",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="auditreponse",
            name="signature_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="auditreponse",
            name="telephone_signataire",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="auditreponse",
            name="user_agent",
            field=models.TextField(blank=True, default=""),
        ),
    ]
