# Generated by Django 6.0.6 on 2026-07-08 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0009_auditreponse_ip_address_auditreponse_nom_signataire_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientDossierCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_month", models.CharField(max_length=4, unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-sequence_month"],
            },
        ),
        migrations.CreateModel(
            name="ClientDossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dossier_id",
                    models.CharField(db_index=True, max_length=16, unique=True),
                ),
                ("sequence_month", models.CharField(db_index=True, max_length=4)),
                ("sequence_number", models.PositiveIntegerField()),
                (
                    "phase",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Contact"),
                            (1, "Diagnostic"),
                            (2, "Proposition"),
                            (3, "Contrat"),
                            (4, "En cours"),
                            (5, "Tests / recette"),
                            (6, "Livraison"),
                            (7, "Suivi"),
                            (8, "Archivé"),
                        ],
                        default=0,
                    ),
                ),
                ("email", models.EmailField(blank=True, db_index=True, max_length=180)),
                ("name", models.CharField(blank=True, max_length=180)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("source", models.CharField(blank=True, max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sequence_month", "sequence_number"),
                        name="client_dossier_month_sequence_unique",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="auditdossier",
            name="client_dossier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_dossiers",
                to="audits.clientdossier",
            ),
        ),
        migrations.AddField(
            model_name="rdv",
            name="client_dossier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rdvs",
                to="audits.clientdossier",
            ),
        ),
        migrations.AddField(
            model_name="rdvcontact",
            name="client_dossier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rdv_contacts",
                to="audits.clientdossier",
            ),
        ),
        migrations.AddField(
            model_name="refonteaudit",
            name="client_dossier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refonte_audits",
                to="audits.clientdossier",
            ),
        ),
        migrations.CreateModel(
            name="DossierLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_phase",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Contact"),
                            (1, "Diagnostic"),
                            (2, "Proposition"),
                            (3, "Contrat"),
                            (4, "En cours"),
                            (5, "Tests / recette"),
                            (6, "Livraison"),
                            (7, "Suivi"),
                            (8, "Archivé"),
                        ]
                    ),
                ),
                (
                    "new_phase",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Contact"),
                            (1, "Diagnostic"),
                            (2, "Proposition"),
                            (3, "Contrat"),
                            (4, "En cours"),
                            (5, "Tests / recette"),
                            (6, "Livraison"),
                            (7, "Suivi"),
                            (8, "Archivé"),
                        ]
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("reason", models.CharField(blank=True, max_length=180)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_dossier_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="audits.clientdossier",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
