# Generated by Django 6.0.6 on 2026-10-06 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0010_clientdossiercounter_clientdossier_and_more'),
        ('crm', '0003_notification_contact_request_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdossier',
            name='followup_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditdossier_followup', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='rdv',
            name='followup_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdv_followup', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='refonteaudit',
            name='followup_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refonteaudit_followup', to='crm.contact'),
        ),
    ]
