# Generated by Django 6.0.6 on 2026-10-06 14:51

import django.contrib.postgres.constraints
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0011_auditdossier_followup_contact_rdv_followup_contact_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='creneaucalendrier',
            constraint=models.CheckConstraint(condition=models.Q(('heure_fin__gt', models.F('heure_debut'))), name='creneau_positive_duration'),
        ),
        migrations.AddConstraint(
            model_name='creneaucalendrier',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('statut__in', ['reserve_audit', 'reserve_intervention', 'bloque'])), expressions=[(django.db.models.expressions.RawSQL("tsrange(date + heure_debut, date + heure_fin, '[)')", []), '&&')], name='creneau_no_reserved_overlap'),
        ),
    ]
