# Generated by Django 6.0.6 on 2026-07-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audits", "0010_clientdossiercounter_clientdossier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                (
                    "format_type",
                    models.CharField(
                        choices=[
                            ("presentiel", "Présentiel"),
                            ("distanciel", "Distanciel"),
                            ("hybride", "Hybride"),
                        ],
                        max_length=32,
                    ),
                ),
                ("duration_hours", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("max_participants", models.PositiveIntegerField(default=10)),
                ("scheduled_dates", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("icon", models.CharField(blank=True, max_length=80)),
                (
                    "service_category",
                    models.CharField(
                        choices=[
                            ("developpement", "Développement"),
                            ("materiel", "Matériel"),
                            ("formation", "Formation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=180)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("audit_site", "Audit sécurité de site web"),
                            ("site_maintenable", "Site sobre, sécurisé, maintenable"),
                            (
                                "maintenance_documentation",
                                "Maintenance, accès et documentation",
                            ),
                            ("urgence", "Urgence : site cassé, piraté ou inaccessible"),
                            ("developpement", "Développement Web/Applicatif"),
                            ("materiel", "Réparation/Reconditionnement"),
                            ("formation", "Formation & Hygiène Numérique"),
                            ("autre", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField()),
                ("read", models.BooleanField(default=False)),
                ("notification_status", models.JSONField(blank=True, default=dict)),
                (
                    "client_dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_contacts",
                        to="audits.clientdossier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormationRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=180)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("number_of_participants", models.PositiveIntegerField(default=1)),
                ("special_needs", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "client_dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="formation_registrations",
                        to="audits.clientdossier",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="crm.formation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=180)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("budget", models.CharField(blank=True, max_length=80)),
                ("project_description", models.TextField()),
                ("timeline", models.CharField(blank=True, max_length=120)),
                (
                    "lead_type",
                    models.CharField(
                        choices=[
                            ("developpement", "Développement"),
                            ("materiel", "Matériel"),
                            ("formation", "Formation"),
                            ("autre", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("contacted", "Contacté"),
                            ("qualified", "Qualifié"),
                            ("closed", "Clôturé"),
                        ],
                        default="new",
                        max_length=32,
                    ),
                ),
                (
                    "client_dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_leads",
                        to="audits.clientdossier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
