# Generated by Django 6.0.6 on 2026-07-08 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0010_clientdossiercounter_clientdossier_and_more"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="demand_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("diagnostic", "Diagnostic"),
                    ("urgency", "Urgence"),
                    ("audit", "Audit"),
                    ("refonte", "Refonte"),
                    ("transmission", "Transmission"),
                    ("partnership", "Partenariat / autre"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="secret_token",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Ouvert"),
                    ("in_progress", "En cours"),
                    ("waiting_customer", "En attente client"),
                    ("resolved", "Résolu"),
                    ("closed", "Clôturé"),
                ],
                default="open",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="ticket_id",
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.CharField(
                        choices=[
                            ("customer", "Client"),
                            ("support", "Support"),
                            ("system", "Système"),
                        ],
                        default="customer",
                        max_length=24,
                    ),
                ),
                ("author_name", models.CharField(max_length=160)),
                ("message", models.TextField()),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="crm.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosticTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ticket_id", models.CharField(blank=True, max_length=32, unique=True)),
                ("organization", models.CharField(max_length=160)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("message", models.TextField()),
                ("status", models.CharField(default="open", max_length=32)),
                ("answers", models.JSONField(blank=True, default=dict)),
                ("diagnostic_result", models.JSONField(blank=True, default=dict)),
                ("email_confirmation", models.JSONField(blank=True, default=dict)),
                (
                    "client_dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnostic_tickets",
                        to="audits.clientdossier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
