# Generated by Django 6.0.6 on 2026-07-14 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0010_clientdossiercounter_clientdossier_and_more"),
        ("crm", "0003_contact_dossier_authority"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contact",
            name="crm_contact_phone_required",
        ),
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name="contact",
            name="demand_type",
            field=models.CharField(
                choices=[
                    ("diagnostic", "Diagnostic"),
                    ("urgency", "Urgence"),
                    ("audit", "Audit"),
                    ("refonte", "Refonte"),
                    ("transmission", "Transmission"),
                    ("partnership", "Partenariat / autre"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                max_length=40,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le numéro de téléphone doit être un numéro français valide.",
                        regex="^0[67][0-9]{8}$",
                    )
                ],
            ),
        ),
    ]
