# Generated by Django 6.0.6 on 2026-07-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_remove_contact_crm_contact_phone_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="demand_type",
            field=models.CharField(
                choices=[
                    ("diagnostic", "Diagnostic"),
                    ("urgency", "Urgence"),
                    ("audit", "Audit"),
                    ("refonte", "Refonte"),
                    ("transmission", "Transmission"),
                    (
                        "materiel",
                        "Matériel : réparation, reconditionnement, migration Linux",
                    ),
                    ("partnership", "Partenariat / autre"),
                ],
                max_length=32,
            ),
        ),
    ]
