# Generated by Django 6.0.6 on 2026-10-06 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_notification_contact_request_context_and_more'),
        ('urgencies', '0002_urgencyrequest_client_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencyrequest',
            name='followup_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urgencyrequest_followup', to='crm.contact'),
        ),
    ]
