# Generated by Django 6.0.6 on 2026-07-19 21:01

import catalogue.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefurbishedMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("archived", "Archivé"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("internal_reference", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=180,
                        validators=[catalogue.validators.validate_plain_text],
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[catalogue.validators.validate_plain_text],
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        max_length=140,
                        validators=[catalogue.validators.validate_plain_text],
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        max_length=320,
                        validators=[catalogue.validators.validate_plain_text],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(10000),
                            catalogue.validators.validate_plain_text,
                        ],
                    ),
                ),
                (
                    "cosmetic_condition",
                    models.CharField(
                        blank=True,
                        max_length=240,
                        validators=[catalogue.validators.validate_plain_text],
                    ),
                ),
                (
                    "installed_operating_system",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        validators=[catalogue.validators.validate_plain_text],
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[catalogue.validators.validate_structured_entries],
                    ),
                ),
                (
                    "performed_interventions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[catalogue.validators.validate_structured_entries],
                    ),
                ),
                (
                    "performed_tests",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[catalogue.validators.validate_structured_entries],
                    ),
                ),
                (
                    "commercial_status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("reserved", "Réservée"),
                            ("sold", "Vendue"),
                            ("archived", "Archivée"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=16,
                    ),
                ),
                (
                    "price_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("EUR", "EUR")], default="EUR", max_length=3
                    ),
                ),
                (
                    "warranty_information",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        validators=[catalogue.validators.validate_plain_text],
                    ),
                ),
                (
                    "availability_note",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        validators=[catalogue.validators.validate_plain_text],
                    ),
                ),
                ("featured", models.BooleanField(db_index=True, default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        validators=[catalogue.validators.validate_plain_text],
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        validators=[catalogue.validators.validate_plain_text],
                    ),
                ),
                ("available_since", models.DateField(blank=True, null=True)),
                ("reserved_at", models.DateTimeField(blank=True, null=True)),
                ("sold_at", models.DateTimeField(blank=True, null=True)),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(5000),
                            catalogue.validators.validate_plain_text,
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(app_label)s_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(app_label)s_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-featured", "display_order", "-published_at", "id"],
                "permissions": [
                    (
                        "edit_refurbishedmachine_drafts",
                        "Peut modifier les brouillons du catalogue",
                    ),
                    (
                        "publish_refurbishedmachine",
                        "Peut publier les machines reconditionnées",
                    ),
                    (
                        "change_refurbishedmachine_commercial_status",
                        "Peut changer le statut commercial",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("price_amount__isnull", True),
                            ("price_amount__gte", 0),
                            _connector="OR",
                        ),
                        name="catalogue_machine_price_non_negative",
                    )
                ],
            },
        ),
    ]
